apiVersion: apps/v1
kind: Deployment

metadata:
  name: hermes

spec:
  selector:
    matchLabels:
      app: hermes

  template:
    metadata:
      labels:
        app: hermes

    spec:
      containers:
        - command:
            - /bin/bash
            - -c
            - |
                #!/bin/bash

                set -o errexit -o errtrace

                AGORIC_CHAIN_HERMES_ACCOUNT_MNEMONIC="orbit bench unit task food shock brand bracket domain regular warfare company announce wheel grape trust sphere boy doctor half guard ritual three ecology"
                AGORIC_KEY_NAME="My Wallet"
                OSMOSIS_CHAIN_ID="osmo-test-5"
                OSMOSIS_CHAIN_HERMES_ACCOUNT_MNEMONIC="orbit bench unit task food shock brand bracket domain regular warfare company announce wheel grape trust sphere boy doctor half guard ritual three ecology"
                OSMOSIS_KEY_NAME="My Wallet"

                mkdir --parents $HOME/.hermes
                touch "$HOME/.hermes/config.toml"

                cat << EOF > $HOME/.hermes/config.toml
                [global]
                log_level = "info"

                [mode.clients]
                enabled = true
                refresh = true
                misbehaviour = true

                [mode.connections]
                enabled = false

                [mode.channels]
                enabled = false

                [mode.packets]
                enabled = true
                clear_interval = 100
                clear_on_start = true
                tx_confirmation = false
                auto_register_counterparty_payee = false
                clear_limit = 50

                [mode.packets.ics20_max_memo_size]
                enabled = true
                size = 32768

                [mode.packets.ics20_max_receiver_size]
                enabled = true
                size = 2048

                [rest]
                enabled = false
                host = "127.0.0.1"
                port = 3000

                [telemetry]
                enabled = false
                host = "127.0.0.1"
                port = 3001

                [telemetry.buckets.latency_submitted]
                start = 500
                end = 20000
                buckets = 10

                [telemetry.buckets.latency_confirmed]
                start = 1000
                end = 30000
                buckets = 10

                [[chains]]
                type = "CosmosSdk"
                id = "$CHAIN_ID"
                rpc_addr = "http://$RPCNODES_SERVICE_HOST:26657"
                grpc_addr = "http://$RPCNODES_SERVICE_HOST:9090"
                rpc_timeout = "10s"
                trusted_node = false
                account_prefix = "agoric"
                key_name = "$AGORIC_KEY_NAME"
                key_store_type = "Test"
                store_prefix = "ibc"
                default_gas = 100000
                max_gas = 400000
                gas_multiplier = 1.1
                max_msg_num = 30
                max_tx_size = 180000
                max_grpc_decoding_size = 33554432
                query_packets_chunk_size = 50
                clock_drift = "5s"
                max_block_time = "30s"
                client_refresh_rate = "1/3"
                ccv_consumer_chain = false
                memo_prefix = ""
                sequential_batch_tx = false
                allow_ccq = true

                [chains.event_source]
                mode = "pull"
                interval = "500ms"
                max_retries = 4

                [chains.trust_threshold]
                numerator = 2
                denominator = 3

                [chains.gas_price]
                price = 0.05
                denom = "ubld"

                [chains.packet_filter]
                policy = "allow"
                list = [[
                  "channel-0",
                  "transfer",
                ]]

                [chains.packet_filter.min_fees]

                [chains.dynamic_gas_price]
                enabled = false
                multiplier = 1.1
                max = 0.6

                [chains.address_type]
                derivation = "cosmos"

                [chains.excluded_sequences]

                [[chains]]
                type = "CosmosSdk"
                id = "$OSMOSIS_CHAIN_ID"
                rpc_addr = "https://rpc.testnet.osmosis.zone"
                grpc_addr = "https://grpc.testnet.osmosis.zone"
                rpc_timeout = "10s"
                trusted_node = false
                account_prefix = "osmo"
                key_name = "$OSMOSIS_KEY_NAME"
                key_store_type = "Test"
                store_prefix = "ibc"
                default_gas = 100000
                max_gas = 400000
                gas_multiplier = 1.1
                max_msg_num = 30
                max_tx_size = 180000
                max_grpc_decoding_size = 33554432
                query_packets_chunk_size = 50
                clock_drift = "5s"
                max_block_time = "30s"
                client_refresh_rate = "1/3"
                ccv_consumer_chain = false
                memo_prefix = ""
                sequential_batch_tx = false
                allow_ccq = true

                [chains.event_source]
                mode = "pull"
                interval = "500ms"
                max_retries = 4

                [chains.trust_threshold]
                numerator = 2
                denominator = 3

                [chains.gas_price]
                price = 0.025
                denom = "uosmo"

                [chains.packet_filter]
                policy = "allow"
                list = [[
                  "channel-8879",
                  "transfer",
                ]]

                [chains.packet_filter.min_fees]

                [chains.dynamic_gas_price]
                enabled = true
                multiplier = 1.1
                max = 0.6

                [chains.address_type]
                derivation = "cosmos"

                [chains.excluded_sequences]

                [tracing_server]
                enabled = false
                port = 5555
                EOF

                echo "$AGORIC_CHAIN_HERMES_ACCOUNT_MNEMONIC" > agoric-chain-mnemonic.json
                echo "$OSMOSIS_CHAIN_HERMES_ACCOUNT_MNEMONIC" > osmosis-chain-mnemonic.json

                hermes keys add \
                 --chain=$CHAIN_ID --key-name="$AGORIC_KEY_NAME" --mnemonic-file=agoric-chain-mnemonic.json
                hermes keys add \
                 --chain="$OSMOSIS_CHAIN_ID" --key-name="$OSMOSIS_KEY_NAME" --mnemonic-file=osmosis-chain-mnemonic.json

                rm agoric-chain-mnemonic.json osmosis-chain-mnemonic.json

                hermes create channel \
                 --a-chain=$OSMOSIS_CHAIN_ID --a-port=transfer --b-chain=$CHAIN_ID --b-port=transfer --new-client-connection

                hermes start
          env:
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  key: CHAIN_ID
                  name: instagoric-release
          image: informalsystems/hermes:1.10.3
          name: hermes-relayer
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 400Mi
