apiVersion: apps/v1
kind: Deployment

metadata:
  name: relayer

spec:
  selector:
    matchLabels:
      app: relayer

  template:
    metadata:
      labels:
        app: relayer

    spec:
      containers:
        - command:
            - /bin/bash
            - -c
            - |
                #!/bin/bash

                set -o errexit -o errtrace -o xtrace

                EXTERNAL_CHAIN_ADDRESS_PREFIX="osmo"
                EXTERNAL_CHAIN_DENOM="uosmo"
                EXTERNAL_CHAIN_ID="osmo-test-5"
                EXTERNAL_CHAIN_NAME="osmosis"
                EXTERNAL_CHAIN_RPC="https://rpc.testnet.osmosis.zone"
                export HOME_PATH="$HOME/.relayer"
                INTERNAL_CHAIN_ADDRESS_PREFIX="agoric"
                INTERNAL_CHAIN_DENOM="ubld"
                INTERNAL_CHAIN_NAME="agoric"
                INTERNAL_CHAIN_RPC="http://$RPCNODES_SERVICE_HOST:$RPCNODES_SERVICE_PORT"
                MNEMONIC="talk prepare desk time attract morning grow arrange buddy appear spring bring genuine deer any mercy lizard wife local runway tennis erode auction square"

                mkdir --parents $HOME_PATH

                cat << EOF > $HOME_PATH/registry.yaml
                chains:
                  $EXTERNAL_CHAIN_NAME:
                    chain_id: $EXTERNAL_CHAIN_ID
                    hd_path: m/44'/1234'/0'/2'
                    estimated_block_time: 6000
                    estimated_indexer_time: 100
                    gas_price: 0.025$EXTERNAL_CHAIN_DENOM
                    ics20_port: transfer
                    prefix: $EXTERNAL_CHAIN_ADDRESS_PREFIX
                    rpc:
                      - $EXTERNAL_CHAIN_RPC
                  $INTERNAL_CHAIN_NAME:
                    chain_id: $CHAIN_ID
                    hd_path: m/44'/1234'/0'/1'
                    estimated_block_time: 6000
                    estimated_indexer_time: 100
                    gas_price: 0.025$INTERNAL_CHAIN_DENOM
                    ics20_port: transfer
                    prefix: $INTERNAL_CHAIN_ADDRESS_PREFIX
                    rpc:
                      - $INTERNAL_CHAIN_RPC
                version: 1
                EOF

                cat << EOF > $HOME_PATH/app.yaml
                dest: $EXTERNAL_CHAIN_NAME
                mnemonic: $MNEMONIC
                src: $INTERNAL_CHAIN_NAME
                EOF

                cat << 'EOF' > "/usr/src/agoric-sdk/patches/@confio+relayer+0.11.3.patch"
                diff --git a/node_modules/@confio/relayer/build/binary/create-logger.js b/node_modules/@confio/relayer/build/binary/create-logger.js
                index e0ea321..876b412 100644
                --- a/node_modules/@confio/relayer/build/binary/create-logger.js
                +++ b/node_modules/@confio/relayer/build/binary/create-logger.js
                @@ -79,1 +79,1 @@             ...(stackTrace ? {} : { stack: undefined }), // remove `stack` from the output if no --stack-trace is provided
                -        });
                +        }, (key, value) => typeof value === 'bigint' ? value.toString() : value);
                EOF

                yarn --cwd=/usr/src/agoric-sdk patch-package

                agoric ibc-setup ics20 --home="$HOME_PATH"
                agoric ibc-relayer start --home="$HOME_PATH" --log-level=debug --poll=10
          env:
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  key: CHAIN_ID
                  name: instagoric-release
          image: ghcr.io/agoric/agoric-sdk
          name: relayer
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 400Mi
