apiVersion: apps/v1
kind: Deployment

metadata:
  name: relayer

spec:
  selector:
    matchLabels:
      app: relayer

  template:
    metadata:
      labels:
        app: relayer

    spec:
      containers:
        - command:
            - /bin/bash
            - -c
            - |
                #!/bin/bash

                set -o errexit -o errtrace -o xtrace

                EXTERNAL_CHAIN_ID="uni-6"
                HOME_PATH="$HOME/.relayer"
                MNEMONIC="orbit bench unit task food shock brand bracket domain regular warfare company announce wheel grape trust sphere boy doctor half guard ritual three ecology"

                mkdir --parents $HOME_PATH

                cat << EOF > $HOME_PATH/registry.yaml
                chains:
                  agoric:
                    chain_id: $CHAIN_ID
                    hd_path: m/44'/1234'/0'/1'
                    estimated_block_time: 6000
                    estimated_indexer_time: 100
                    gas_price: 0.025ubld
                    ics20_port: transfer
                    prefix: agoric
                    rpc:
                      - http://$RPCNODES_SERVICE_HOST:$RPCNODES_SERVICE_PORT
                  juno:
                    chain_id: $EXTERNAL_CHAIN_ID
                    hd_path: m/44'/1234'/0'/2'
                    estimated_block_time: 6000
                    estimated_indexer_time: 100
                    gas_price: 0.025ujunox
                    ics20_port: transfer
                    prefix: juno
                    rpc:
                      - https://juno-testnet-rpc.polkachu.com
                version: 1
                EOF

                cat << EOF > $HOME_PATH/app.yaml
                dest: juno
                mnemonic: $MNEMONIC
                src: agoric
                EOF

                agoric ibc-setup ics20 --home="$HOME_PATH"
                agoric ibc-relayer start --home="$HOME_PATH"
          env:
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  key: CHAIN_ID
                  name: instagoric-release
          image: ghcr.io/agoric/agoric-sdk
          name: relayer
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 400Mi
