apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: instagoric

resources:
  - ../../bases/shared
  - ../../bases/primaryvalidator
  - ../../bases/validators
  - ../../bases/rpcnodes
  - ../../bases/seed
  - ../../bases/explorer

patches:
  - target:
      kind: StatefulSet
      name: validator
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
