apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentracing-agent-${namespace}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentracing-agent
rules:
  - apiGroups: ["", "apps"]
    resources:
      - configmaps
      - daemonsets
      - deployments
      - endpoints
      - events
      - namespaces
      - nodes
      - nodes/metrics
      - nodes/stats
      - pods
      - replicasets
      - services
      - statefulsets
    verbs: ["delete", "get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentracing-agent-${namespace}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: ClusterRole
  name: opentracing-agent
subjects:
  - kind: ServiceAccount
    name: opentracing-agent-${namespace}
    namespace: ${namespace}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opentracing-agent-${namespace}
  namespace: ${namespace}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: ClusterRole
  name: opentracing-agent
subjects:
  - kind: ServiceAccount
    name: opentracing-agent-${namespace}
    namespace: ${namespace}
