apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: grpc-backendconfig
spec:
  healthCheck:
    port: 8080
    requestPath: /
    type: HTTP
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-backendconfig
spec:
  healthCheck:
    port: 1317
    requestPath: /node_info
    type: HTTP
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: rpc-backendconfig
spec:
  healthCheck:
    port: 26657
    requestPath: /abci_info
    type: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: rpcnodes
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
    cloud.google.com/backend-config: '{"ports":{"grpc":"grpc-backendconfig","api":"api-backendconfig","rpc":"rpc-backendconfig"}}'
    cloud.google.com/neg: '{"ingress":true,"exposed_ports":{"26657":{},"1317":{},"9090":{},"8001":{}}}'
spec:
  type: ClusterIP
  selector:
    grouplb: validator
  ports:
  - protocol: TCP
    targetPort: 26657
    port: 26657
    name: rpc
  - protocol: TCP
    targetPort: 1317
    port: 1317
    name: api
  - protocol: TCP
    targetPort: 9090
    port: 9090
    name: grpc
  - protocol: TCP
    targetPort: 8001
    port: 8001
    name: sidekick
  - protocol: TCP
    targetPort: 8003
    port: 8003
    name: sidekickfaucet
