apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../node

patches:
  - target:
      kind: StatefulSet
      name: node
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 2000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 2000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 20Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 20Gi
      - op: replace
        path: /spec/replicas
        value: 3
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: 
          name: ROLE
          value: validator
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: 
          name: USE_OTEL_CONFIG
          value: /config/otel/otel-config.yaml
      - op: replace
        path: /spec/selector/matchLabels/app
        value: validator
      - op: replace
        path: /metadata/name
        value: validator
      - op: add
        path: /metadata/labels
        value: 
          app: validator
      - op: add
        path: /spec/serviceName
        value: rpcnodes
      - op: add
        path: /spec/template/metadata/labels/app
        value: validator
      - op: add
        path: /spec/template/metadata/labels/grouplb
        value: validator
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://localhost:4318/v1/traces
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SLOGSENDER
          valueFrom:
            configMapKeyRef:
              name: otel-config
              key: SLOGSENDER
              optional: true
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 300Gi