apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: relayer

spec:
  replicas: 1
  selector:
    matchLabels:
      app: relayer
  serviceName: relayer

  template:
    metadata:
      labels:
        app: relayer

    spec:
      containers:
        - command:
            - /bin/bash
            - /root/scripts/entrypoint.sh
          env:
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  key: CHAIN_ID
                  name: instagoric-release
            - name: RELAYER_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  key: RELAYER_CONNECTIONS
                  name: instagoric-release
                  optional: true
            - name: RELAYER_MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: instagoric-secrets
                  key: HERMES_SEED
                  optional: true
            - name: RELAYER_HOME
              value: /relayer
          image: debian:bullseye
          name: relayer
          resources:
            limits:
              cpu: 2000m
              ephemeral-storage: 8Gi
              memory: 4Gi
            requests:
              cpu: 1000m
              ephemeral-storage: 4Gi
              memory: 4Gi
          volumeMounts:
            - mountPath: /root/scripts
              name: helpers
            - mountPath: /relayer
              name: state
      volumes:
        - configMap:
            name: relayer-helpers
          name: helpers

  volumeClaimTemplates:
    - metadata:
        name: state
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 4Gi
