apiVersion: apps/v1
kind: Deployment

metadata:
  name: relayer-test

spec:
  selector:
    matchLabels:
      app: relayer-test

  template:
    metadata:
      labels:
        app: relayer-test

    spec:
      containers:
        - command:
            - /bin/bash
            - -x
            - /root/scripts/entrypoint.sh
          env:
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  key: CHAIN_ID
                  name: instagoric-release
            - name: EXTERNAL_CHAIN_NAME
              valueFrom:
                configMapKeyRef:
                  key: EXTERNAL_CHAIN_NAME
                  name: instagoric-release
                  optional: true
            - name: INTERNAL_CHAIN_ADDRESS_PREFIX
              valueFrom:
                configMapKeyRef:
                  key: INTERNAL_CHAIN_ADDRESS_PREFIX
                  name: instagoric-release
                  optional: true
            - name: INTERNAL_CHAIN_GAS_DENOM
              valueFrom:
                configMapKeyRef:
                  key: INTERNAL_CHAIN_GAS_DENOM
                  name: instagoric-release
                  optional: true
            - name: IS_EXTERNAL_CHAIN_TESTNET
              valueFrom:
                configMapKeyRef:
                  key: IS_EXTERNAL_CHAIN_TESTNET
                  name: instagoric-release
                  optional: true
          image: debian:bullseye
          name: relayer-test
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
          volumeMounts:
            - mountPath: /root/scripts
              name: helpers
      volumes:
        - configMap:
            name: relayer-helpers
          name: helpers
