apiVersion: kustomize.config.k8s.io/v1beta1

configMapGenerator:
  - name: relayer-helpers
    files:
      - entrypoint.sh
      - current-chain.sh
      - current-chain-post.sh
      - devnet.sh
      - ollinet.sh
      - osmosistestnet-post.sh

kind: Kustomization

resources:
  - deployment.yaml
