apiVersion: kustomize.config.k8s.io/v1beta1

configMapGenerator:
  - name: relayer-helpers
    files:
      - add-agoric-chain.sh
      - cosmoshubtestnet.sh
      - current-chain.sh
      - current-chain-pre.sh
      - devnet.sh
      - entrypoint.sh
      - nobletestnet.sh
      - nobletestnet-pre.sh
      - ollinet.sh
      - osmosistestnet-post.sh

kind: Kustomization

resources:
  - deployment.yaml
