apiVersion: apps/v1
kind: Deployment

metadata:
  name: explorer

spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer
  template:
    metadata:
      labels:
        app: explorer
    spec:
      containers:
        - args: ["/entrypoint/entrypoint.sh"]
          command: ["/bin/bash"]
          image: "node:20-bullseye"
          name: explorer
          ports:
            - containerPort: 8080
              name: web
          resources:
            limits:
              cpu: 2000m
              ephemeral-storage: 8Gi
              memory: 8Gi
            requests:
              cpu: 1000m
              ephemeral-storage: 5Gi
              memory: 4Gi
          volumeMounts:
            - mountPath: /entrypoint
              name: entrypoint
      volumes:
        - configMap:
            name: "explorer-entrypoint"
          name: entrypoint
      terminationGracePeriodSeconds: 10
