apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer
spec:
  selector:
    matchLabels:
      app: explorer
  replicas: 1
  template:
    metadata:
      labels:
        app: explorer
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: explorer
          image: "ghcr.io/arirubinstein/explorer:20230320193238-3fc64c-linux_amd64"
          command: ["/bin/sh"]
          args: ["-x", "/entrypoint/entrypoint.sh"]
          env:
            - name: NETNAME
              valueFrom:
                configMapKeyRef:
                  name: instagoric-release
                  key: NETNAME
            - name: NETDOMAIN
              valueFrom:
                configMapKeyRef:
                  name: instagoric-release
                  key: NETDOMAIN
                  optional: true
          ports:
            - containerPort: 8080
              name: web
          volumeMounts:
            - name: entrypoint
              mountPath: /entrypoint
          resources:
            limits:
              cpu: 1000m
              ephemeral-storage: 5Gi
              memory: 4Gi
            requests:
              cpu: 1000m
              ephemeral-storage: 5Gi
              memory: 4Gi
      volumes:
        - name: entrypoint
          configMap:
            name: explorerentrypoint
