apiVersion: kustomize.config.k8s.io/v1beta1

configMapGenerator:
  - name: "explorer-entrypoint"
    files:
      - agoric.json
      - agoric.png
      - agoric-bld.svg
      - entrypoint.sh

kind: Kustomization

resources:
  - explorer.yaml
  - service.yaml
