apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../node

commonLabels:
  app: ag-solo-tasks
configMapGenerator:
  - name: tasks
    files:
      - tasks/loaded.js
      - tasks/amm_swap.js

patches:
  - target:
      kind: StatefulSet
      name: node
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 2Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 2Gi
      - op: replace
        path: /spec/replicas
        value: 5
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: 
          name: ROLE
          value: ag-solo
      - op: replace
        path: /spec/selector/matchLabels/app
        value: ag-solo-tasks
      - op: replace
        path: /metadata/name
        value: ag-solo-tasks
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: tasks
          mountPath: /tasks
      - op: add
        path: /spec/template/spec/volumes/-
        value: 
          name: tasks
          configMap:
            name: tasks
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: 
          name: SUBROLE
          value: tasks
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: 
          name: TASKS
          value: auto
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: 
          name: SOLO_FUNDING_AMOUNT
          value: 9000000000000000ubld,9000000000000000uist,1provisionpass
