apiVersion: v1
kind: Service
metadata:
  name: seed
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    app: seed
  ports:
    - name: p2p
      port: 26656
      protocol: TCP
      targetPort: 26656
    - name: rpc
      port: 26657
      protocol: TCP
      targetPort: 26657

---
apiVersion: v1
kind: Service
metadata:
  name: seed-ext
spec:
  type: LoadBalancer
  selector:
    app: seed
  sessionAffinity: "ClientIP"
  ports:
    - name: p2p
      port: 26656
      protocol: TCP
      targetPort: 26656
